apiVersion: v1
kind: Service
metadata:
  name: neon
  labels:
    app: neon
spec:
  ports:
    - port: 80
  selector:
    app: nginx
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: neon-backend
  labels:
    app: neon
spec:
  selector:
    matchLabels:
      app: neon
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neon
        tier: frontend
    spec:
      containers:
      - image: tecty/neon-backend 
        name: web
        env:
        - name: DB_HOST
          value: neon-pgsql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: username
      - image: tecty/neon-nginx 
        name: neon
        ports:
        - containerPort: 80
          name: nginx
      #   ports:
      #   - containerPort:80
      #     name: backend