@auth = JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InR0dCIsImV4cCI6MTU1MTc4NTk1NywiZW1haWwiOiIifQ.QGPf__MF76pMy-IDYsd33rbrkDItF8uVJHL-5zmkvoI
@baseUrl = http://localhost:8000/v0/


POST {{baseUrl}}jwt/ HTTP/1.1
Content-Type: application/json

{
	"username": "ttt" ,
	"password": "apple123"
}



###

# register User
POST {{baseUrl}}users/ HTTP/1.1
Content-Type: application/json

{
    "username": "ttt",
    "password": "apple123",
    "first_name": "Toby",
    "last_name": "HUANG"
}


###
# get article 
GET {{baseUrl}}articles/ HTTP/1.1
Content-Type: application/json

{}

###
# create article 

POST {{baseUrl}}articles/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    "url": "http://localhost:8000/v0/article/",
    "headline": "another",
    "publish": "0200-01-01T15:20:00Z",
    "main_text": "helloworld",
    "p_fuzz": "M"
}


###
# Get locations

GET {{baseUrl}}location/ HTTP/1.1
Content-Type: application/json

{}

###
# Create locations

POST  {{baseUrl}}location/ HTTP/1.1
Content-Type: application/json

{
    "name": "Sydney",
    "lat": 12.22,
    "lng": 22.33
}



###
# Get diseases

GET {{baseUrl}}location/ HTTP/1.1
Content-Type: application/json

{}

###
# Create diseases

POST  {{baseUrl}}location/ HTTP/1.1
Content-Type: application/json

{
    "name": "Sydney",
    "lat": 12.22,
    "lng": 22.33
}
