# Generated by Django 2.1.7 on 2019-04-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20190403_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish',
            new_name='date_of_publication',
        ),
    ]
