# Generated by Django 2.1.7 on 2019-04-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20190403_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('img', models.URLField(blank=True)),
                ('key_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Disease')),
            ],
            options={
                'verbose_name': 'outbreak',
                'verbose_name_plural': 'outbreaks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='outbreak',
            unique_together={('key_term', 'start_date', 'end_date')},
        ),
    ]
