# Generated by Django 2.1.7 on 2019-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20190419_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreak',
            name='img',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
