# Generated by Django 2.1.7 on 2019-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='p_fuzz',
            field=models.CharField(choices=[('Y', 'Year'), ('M', 'Month'), ('D', 'Day'), ('H', 'Hour'), ('I', 'Minute'), ('S', 'Second'), ('A', 'Accurate')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='ed_fuzz',
            field=models.CharField(choices=[('Y', 'Year'), ('M', 'Month'), ('D', 'Day'), ('H', 'Hour'), ('I', 'Minute'), ('S', 'Second'), ('A', 'Accurate')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='sd_fuzz',
            field=models.CharField(choices=[('Y', 'Year'), ('M', 'Month'), ('D', 'Day'), ('H', 'Hour'), ('I', 'Minute'), ('S', 'Second'), ('A', 'Accurate')], max_length=1),
        ),
    ]
