# Generated by Django 2.1.7 on 2019-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='syndromes',
            field=models.ManyToManyField(blank=True, to='report.Syndrome'),
        ),
    ]
